##

# Load data

In [7]:
import pandas as pd
from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.impute import SimpleImputer


# File name
# RAW_DATA_FILE_NAME = "loan_data.csv"
RAW_DATA_FILE_NAME = "loan_data_hard_filtered.csv"

PROJECT_ROOT = Path("..")
RAW_DATA_FILE_PATH = PROJECT_ROOT / "data" / "pre-processed" / RAW_DATA_FILE_NAME

OUTPUT_DIR = PROJECT_ROOT / "data" / "pre-processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("Raw data path:", RAW_DATA_FILE_PATH)
print("Output folder:", OUTPUT_DIR)

df = pd.read_csv(RAW_DATA_FILE_PATH)
print(df.shape)
df.head()

PROJECT_ROOT: ..
Raw data path: ../data/pre-processed/loan_data_hard_filtered.csv
Output folder: ../data/pre-processed
(44993, 14)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

# Data Preprocessing

In [8]:
# Remove Bias column
df = df.drop(columns=['previous_loan_defaults_on_file'])

# Ordinal Mapping
EDUCATION_MAPPING_RULES = {
    'High School': 1,
    'Associate': 2,
    'Bachelor': 3,
    'Master': 4,
    'Doctorate': 5
}

df['person_education'] = df['person_education'].map(EDUCATION_MAPPING_RULES)


print("New DataFrame preprocessed shape:", df.shape)
df.head()

New DataFrame preprocessed shape: (44993, 13)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
0,22.0,female,4,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,1
1,21.0,female,1,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,0
2,25.0,female,1,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,1
3,23.0,female,3,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,1
4,24.0,male,4,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,1

## Save preprocessed CSV files

In [9]:
output_path = OUTPUT_DIR / "loan_data_preprocessed.csv"

df.to_csv(output_path, index=False)

print("Saved Pre-processed data to:", output_path)

Saved Pre-processed data to: ../data/pre-processed/loan_data_preprocessed.csv